### ISSUE TITLE
Error in version 1.6.1

### ISSUE THREAD

**Issue by rp1231** [pdone/FreeControl#32]
log:
2023-08-21 15:09:12:079 [ERROR] System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\admin\AppData\Roaming\FreeControl\scrcpy-win64-v2.1.1\'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at FreeControl.Main.ExtractResource(Boolean reload)
   at FreeControl.Main.InitPdone()
   at FreeControl.Main..ctor()
   at FreeControl.Trusteeship..ctor()
   at FreeControl.Program.Main()

**Comment by pdone** [comment]
情况说明：
1.6.1版本增加了更新使用新版本时，删除旧版本的scrcpy资源，删除前忘记判断是否存在了，导致删除失败了，属于非常粗心的bug了，非常抱歉！
请使用1.6.2版本，已增加判断。
------------------------------------
Description:
Version 1.6.1 adds updates. When using the new version, delete the scrcpy resources of the old version, forget to judge whether it exists before deleting, resulting in failure of deletion. It is a very careless bug. I am very sorry!
Please use version 1.6.2, judgment has been added.
