### ISSUE TITLE
连接到手机后，没有下方的控制按钮呢？

### ISSUE THREAD

**Issue by ccliushou** [pdone/FreeControl#48]
![image](https://github.com/pdone/FreeControl/assets/10105646/a09085cf-eb26-4e26-9111-811424506f18)

请问，我用源码启动FreeControl，只有scrcpy的手机屏幕显示，但没有控制下发的的控制按钮呢？？

看不到这些按钮：
![image](https://github.com/pdone/FreeControl/assets/10105646/bb773813-139d-410c-9f0b-0ad6c65d704f)

**Comment by ccliushou** [comment]
日志如下：

2023-12-17 14:51:04:761 [INFO] starting...
2023-12-17 14:51:06:519 [INFO] scrcpy running...
2023-12-17 14:51:06:519 [INFO] --shortcut-mod=lctrl --window-title "FreeControlScrcpy" --prefer-text --select-usb 
2023-12-17 14:51:08:180 [adb exec] adb shell settings get secure default_input_method
2023-12-17 14:51:10:780 [scrcpy] scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
2023-12-17 14:51:11:457 [adb output] com.iflytek.inputmethod.miui/.FlyIME
2023-12-17 14:51:11:458 [scrcpy] INFO: ADB device found:
2023-12-17 14:51:12:108 [scrcpy] INFO:     -->   (usb)      CIJV75YLVSKVQONZ            device  22122RK93C
2023-12-17 14:51:14:065 [scrcpy] C:\Users\12373\AppData\Roaming\FreeControl\scrcpy-win64-v2.3.1\scrcpy-server: 1 file pushed, 0 skipped. 111.0 MB/s (66007 bytes in 0.001s)
2023-12-17 14:51:14:066 [scrcpy] [server] INFO: Device: [Xiaomi] Redmi 22122RK93C (Android 13)
2023-12-17 14:51:14:070 [scrcpy] INFO: Renderer: direct3d
2023-12-17 14:51:14:070 [scrcpy] INFO: Texture: 1080x2400
2023-12-17 14:51:17:782 [scrcpy] [server] ERROR: Could not invoke method
2023-12-17 14:51:17:782 [scrcpy] java.lang.reflect.InvocationTargetException
2023-12-17 14:51:17:782 [scrcpy] 	at java.lang.reflect.Method.invoke(Native Method)
2023-12-17 14:51:17:782 [scrcpy] 	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
2023-12-17 14:51:17:782 [scrcpy] 	at com.genymobile.scrcpy.Device.injectEvent(Device.java:226)
2023-12-17 14:51:17:783 [scrcpy] 	at com.genymobile.scrcpy.Device.injectEvent(Device.java:230)
2023-12-17 14:51:17:783 [scrcpy] 	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:323)
2023-12-17 14:51:17:783 [scrcpy] 	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:138)
2023-12-17 14:51:17:784 [scrcpy] 	at com.genymobile.scrcpy.Controller.control(Controller.java:83)
2023-12-17 14:51:17:784 [scrcpy] 	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
2023-12-17 14:51:17:784 [scrcpy] 	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
2023-12-17 14:51:17:784 [scrcpy] 	at java.lang.Thread.run(Thread.java:1012)
2023-12-17 14:51:17:784 [scrcpy] Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
2023-12-17 14:51:17:784 [scrcpy] 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
2023-12-17 14:51:17:784 [scrcpy] 	at android.os.Parcel.createException(Parcel.java:2995)
2023-12-17 14:51:17:785 [scrcpy] 	at android.os.Parcel.readException(Parcel.java:2978)
2023-12-17 14:51:17:785 [scrcpy] 	at android.os.Parcel.readException(Parcel.java:2920)
2023-12-17 14:51:17:785 [scrcpy] 	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
2023-12-17 14:51:17:785 [scrcpy] 	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
2023-12-17 14:51:17:785 [scrcpy] 	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
2023-12-17 14:51:17:785 [scrcpy] 	... 10 more
2023-12-17 14:51:17:785 [scrcpy] Caused by: android.os.RemoteException: Remote stack trace:
2023-12-17 14:51:17:785 [scrcpy] 	at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:906)
2023-12-17 14:51:17:785 [scrcpy] 	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:617)
2023-12-17 14:51:17:785 [scrcpy] 	at android.os.Binder.execTransactInternal(Binder.java:1285)
2023-12-17 14:51:17:786 [scrcpy] 	at android.os.Binder.execTransact(Binder.java:1249)
2023-12-17 14:51:17:870 [scrcpy] [server] ERROR: Could not invoke method
2023-12-17 14:51:17:870 [scrcpy] java.lang.reflect.InvocationTargetException
2023-12-17 14:51:17:870 [scrcpy] 	at java.lang.reflect.Method.invoke(Native Method)
2023-12-17 14:51:17:870 [scrcpy] 	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:37)
2023-12-17 14:51:17:870 [scrcpy] 	at com.genymobile.scrcpy.Device.injectEvent(Device.java:226)
2023-12-17 14:51:17:870 [scrcpy] 	at com.genymobile.scrcpy.Device.injectEvent(Device.java:230)
2023-12-17 14:51:17:870 [scrcpy] 	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:323)
2023-12-17 14:51:17:870 [scrcpy] 	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:138)
2023-12-17 14:51:17:870 [scrcpy] 	at com.genymobile.scrcpy.Controller.control(Controller.java:83)
2023-12-17 14:51:17:870 [scrcpy] 	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
2023-12-17 14:51:17:871 [scrcpy] 	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
2023-12-17 14:51:17:871 [scrcpy] 	at java.lang.Thread.run(Thread.java:1012)
2023-12-17 14:51:17:871 [scrcpy] Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
2023-12-17 14:51:17:871 [scrcpy] 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
2023-12-17 14:51:17:871 [scrcpy] 	at android.os.Parcel.createException(Parcel.java:2995)
2023-12-17 14:51:17:871 [scrcpy] 	at android.os.Parcel.readException(Parcel.java:2978)
2023-12-17 14:51:17:871 [scrcpy] 	at android.os.Parcel.readException(Parcel.java:2920)
2023-12-17 14:51:17:871 [scrcpy] 	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
2023-12-17 14:51:17:871 [scrcpy] 	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
2023-12-17 14:51:17:871 [scrcpy] 	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
2023-12-17 14:51:17:871 [scrcpy] 	... 10 more
2023-12-17 14:51:18:718 [scrcpy] [server] ERROR: Could not invoke method

**Comment by ccliushou** [comment]
现在通过鼠标可以控制手机了。。

进入开发者选项，打开USB调试(安全设置)

但，还是没看到这个呢？
![image](https://github.com/pdone/FreeControl/assets/10105646/806a17b0-458f-4325-a0f1-2b915a0ff9a6)

**Comment by ccliushou** [comment]
知道原因了。。是需要自己设置的。。
