### ISSUE TITLE
Still on Starting

### ISSUE THREAD

**Issue by muggleL** [pdone/FreeControl#52]
2023-12-18 12:22:12:255 [INFO] starting...
2023-12-18 12:22:12:255 [INFO] scrcpy running...
2023-12-18 12:22:12:255 [INFO] --shortcut-mod=lctrl --window-x=697 --window-y=60 --window-title "FreeControlScrcpy" --prefer-text --no-audio --select-usb 
2023-12-18 12:22:12:276 [ERROR] System.ComponentModel.Win32Exception (0x80004005): 系統找不到指定的檔案。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at FreeControl.Main.RunScrcpy()
   at FreeControl.Main.StartButtonClick(Object sender, EventArgs e)

-------------------------------------------------------------------------------------------------------------------------------
Roaming\FreeControl\scrcpy-win64-v2.3.1
❯ .\adb.exe devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
MV9DBA8L8TBEG6LN        device

**Comment by muggleL** [comment]
Delete the \AppData\Roaming\FreeControl\scrcpy-win64-v2.3.1 directory and then reopen the software.
